### PR TITLE
Fix `ConfigureAdapter` with deferred configuration

### PR DESCRIPTION
**Pull request by tdeekens**
> The pull request closes an issue found by @Kerumen which made the adapter configure with false `adapterArgs` when deferring its configuration.

The issue #324 describes the problem more eloquently than I could.

One plausible solution is outlined in this PR. The adapter has to configure or reconfigure with queued (pending) or applied (from initial state) args. This situation is a bit "tricky" as we can not call `setState` in `componentDidUpdate` and also do not want the adapter be configured first with stale args and then with up-to-date ones.

### CODE REVIEW

**Comment by tdeekens** [comment]
@Kerumen would you mind having a look just to make sure things make sense and I didn't miss anything?

**Comment by tdeekens** [comment]
Thanks. Yeah that's what I am trying to also still wrap my head around. Essentially, I want to be careful with `componentDidUpdate` as `appliedAdapterArgs` is on the state I added the `pendingAdapterArgs` not to be. So they can be queued up e.g. by a deferred configuration or when rendering `ReconfigureFlopflip` components before the adapter is ready.

**Comment by Kerumen** [comment]
@tdeekens It works well! Thanks :)

**Comment by tdeekens** [comment]
Let's release it then.

**Pull request merged**
